### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mysteryx93** [homov/LibMpv#1]
I started looking at your project.

First, it's not running on Linux. It comes down to `libmpv.RootPath` being `/lib/x86_64-linux-gnu` instead of `/usr/lib`

By changing the value manually, it runs. Pause button works; but Resume doesn't?

**Comment by homov** [comment]
You are absolutely right.

To work correctly, you must specify the full path to the folder containing the libmpv library. In the example, I used /lib/x86_64-linux-gnu because the library is located there in my Linux distribution. In my example, there is no cross-platform mechanism for searching the libmpv library. If you need one, you can look at the implementation example https://github.com/lethek/FFmpeg.Loader (you can adapt it to look for libmpg library instead of ffmpeg libraries).

Also, you correctly noted that Resume is not implemented in the example (only Pause).

To implement the Pause/Resume mechanism, you must set the **pause** property to true/false, respectively.

MPV has a lot of different properties, commands and options.

Read MPV documentation:

- https://mpv.io/manual/master/#properties
- https://mpv.io/manual/master/#options
- https://mpv.io/manual/master/#list-of-input-commands


If I have time, I will write a more complete example of using the libmpv library.

**Comment by mysteryx93** [comment]
What are `LibMpv.AutoGen.ClangMacroParser` and `LibMpv.AutoGen.CppSharpUnsafeGenerator` for?

I see it's auto-generating the library's API.

It's pretty sophisticated code you got in there.

**Comment by homov** [comment]
You're right. This is a tool for automatic wrapper generation (libmpv header files are parsed and C# code is generated). The result of the generator work is placed in the LibMpv.Client project (generated directory).

If you don't want to generate a wrapper yourself, you don't need the projects you listed. The LibMpv.Client project already contains the necessary files.

**Comment by mysteryx93** [comment]
Just curious, where did you get that sophisticated library-linking code?

**Comment by homov** [comment]
As I wrote on the first page (in the brief description of the LibMpv.Client project). I took the code from another project (https://github.com/Ruslan-B/FFmpeg.AutoGen) and slightly modified it to generate code for libmpv.
