### ISSUE TITLE
play a video immediately, the video plays in two wrong places.

### ISSUE THREAD

**Issue by neominky** [homov/LibMpv#11]
I am testing the sample code in a WSL environment.
When play a video immediately after running the program, the video plays in two wrong places.
The program screen appears on monitor 1, and the video appears on monitor 2. Monitor 2 is Primary.
Even if there is a 1~2 second delay, the result is the same.
```
public MainViewModel()
    {
        this.Volume = 50;
        PlayBigBuckBunny();  // <-- added this a line      
    }


    [RelayCommand]
    private void PlayBigBuckBunny()
    {
       this.LoadFile("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");
       this.Play();
    }
```

![image](https://github.com/homov/LibMpv/assets/32407205/bd316ad6-bdd8-4570-ab26-ce0ab8d85d8b)

Delay a second
```
    public MainViewModel()
    {
        this.Volume = 50;
        Task.Run(() => {
            Task.Delay(1000).Wait();
            PlayBigBuckBunny();
        });        
    }
```
![image](https://github.com/homov/LibMpv/assets/32407205/53a35681-4541-4328-873c-a18123cb81f6)

**Comment by homov** [comment]
In order for playback to start correctly, you need to make sure:
- an application window has been created
- OpenGL contexts initialized

In your case, the video starts playing before the above has happened. In this case, the libmpv library automatically creates a separate window (since the initialization for using OpenGL has not yet occurred).

The general recommendation is to start playing the video after you are sure that the application window is visible.
