### ISSUE TITLE
using static instead of dynamic library on supported platforms

### ISSUE THREAD

**Issue by ivanjx** [homov/LibMpv#7]
is it possible to get a static library version of libmpv.dll on windows? at least on windows i can already compile all of my native dependencies (including skiasharp) into a single exe with native aot (see https://github.com/AvaloniaUI/Avalonia/issues/9503#issuecomment-1778874856).

**Comment by homov** [comment]
I think it is possible to build a static library of libmpv.
You can see how to build a dynamic library:
https://github.com/shinchiro/mpv-winbuild-cmake or  https://github.com/zhongfly/mpv-winbuild
Changing these examples to build libmpv as a static library will apparently be trivial.

However, you will not be able to use this wrapper, since it is intended for a dynamic library of libmpv

**Comment by ivanjx** [comment]
>However, you will not be able to use this wrapper, since it is intended for a dynamic library of libmpv

how so? skiasharp is just a wrapper around skia and harfbuzz + angle library and i just add my own statically compiled version of those with 0 code changes and it just worked.

**Comment by homov** [comment]
Because there are several ways to build an interface to dynamic libraries. My method will not allow the use of a static library. Sorry, I didn't expect to use it the way you want...
